### ISSUE TITLE
Revision flowchart isn't rendering on public-facing site

### ISSUE THREAD

**Issue by meau** [saa-ts-dacs/saa-ts-dacs.github.io#6]
The revision flowchart (https://github.com/saa-ts-dacs/dacs/blob/master/DACSRevisionProcess.png) isn't rendering on the website (https://github.com/saa-ts-dacs/dacs/blob/master/DACSRevisionProcess.png).

Also yooooo I think I'm the owner of that on LucidChart. Very happy to give that ownership to someone else. Let me know who.

**Comment by gwiedeman** [comment]
The relative link is broken is because the website serves everything from a /dacs subfolder. Fixing it as a relative link will then break it when viewing the `README.md` on Github, so I think the fix is making it a full path to [https://saa-ts-dacs.github.io/dacs/DACSRevisionProcess.png](https://saa-ts-dacs.github.io/dacs/DACSRevisionProcess.png). I'll put in a PR to the DACS repo for this.

For the chart, when TS-DACS eventually needs to change it, they can ask for ownership or just remake it. Even remaking it from the image might actually be easier than managing ownership for it as TS-DACS rotates over time.
